import {createCBAMReportDocument} from './generator';

export function renderCBAMReport(data={}){
 const document=createCBAMReportDocument(data);

 const lines=[];
 lines.push(document.title);
 lines.push(`Generated by: ${document.generated_by}`);
 lines.push(`Date: ${document.created_at}`);
 lines.push('');

 document.sections.forEach(section=>{
  lines.push(section.title);
  lines.push(String(section.content));
  lines.push('');
 });

 return Buffer.from(lines.join('\n'),'utf-8');
}
