export async function renderCBAMPDF(report={}){
 const content={
  document:'CBAM Compliance Assessment Report',
  brand:'CBAMSearch',
  format:'A4',
  pages:[
   {
    heading:'Executive Summary',
    content:report.summary || 'CBAM assessment summary'
   },
   {
    heading:'Product Information',
    content:report.product || 'N/A'
   },
   {
    heading:'CN Code Classification',
    content:report.cn_code || 'N/A'
   },
   {
    heading:'Origin Country',
    content:report.origin || 'N/A'
   },
   {
    heading:'Emission Assessment',
    content:report.emission || 'N/A'
   }
  ],
  footer:'Generated by CBAMSearch'
 };

 return Buffer.from(JSON.stringify(content,null,2));
}
