import {NextResponse} from 'next/server';

export async function POST(request){
 try{
  const body=await request.json();

  const pdf={
   file_name:`CBAM-Report-${body.report_id || 'draft'}.pdf`,
   report_id:body.report_id || null,
   content:{
    title:'CBAM Compliance Assessment Report',
    customer:body.customer || '',
    product:body.product || '',
    cn_code:body.cn_code || '',
    origin:body.origin || '',
    sector:body.sector || '',
    notes:'Generated by CBAMSearch compliance workspace.'
   },
   status:'generated'
  };

  return NextResponse.json({success:true,pdf});
 }catch(error){
  return NextResponse.json({success:false,error:'Invalid request'},{status:400});
 }
}
