import {NextResponse} from 'next/server';
import {uploadReportFile} from '@/lib/storage/supabase';

export async function POST(request){
 try{
  const body=await request.json();

  const pdf={
   file_name:`CBAM-Report-${body.report_id || 'draft'}.pdf`,
   report_id:body.report_id || null,
   content:{
    title:'CBAM Compliance Assessment Report',
    customer:body.customer || '',
    product:body.product || '',
    cn_code:body.cn_code || '',
    origin:body.origin || '',
    sector:body.sector || '',
    notes:'Generated by CBAMSearch compliance workspace.'
   },
   status:'generated'
  };

  const filePath=`reports/${body.report_id || 'draft'}/${pdf.file_name}`;
  const upload=await uploadReportFile(filePath,Buffer.from(JSON.stringify(pdf,null,2),'utf-8'));

  return NextResponse.json({success:true,pdf,storage:upload});
 }catch(error){
  return NextResponse.json({success:false,error:error.message},{status:400});
 }
}
