export const metadata={title:'CBAM Emissions Data Guide — Supplier & Installation Inputs',description:'Understand the embedded-emissions information, supplier data and verification status needed for CBAM preparation.',alternates:{canonical:'/guides/cbam-emissions-data/'}};
export default function Page(){return <main>
<section className="detailHero"><div className="wrap"><div className="eyebrow">EMISSIONS DATA GUIDE</div><h1>Prepare CBAM emissions data around the goods and the production installation.</h1><p className="lead">Good CBAM preparation connects the imported product to its producer, installation, production route, reporting period and the emissions information used in the assessment.</p><div className="detailActions"><a className="btn" href="/cbam-report/?plan=professional">Open Professional Report</a><a className="btn secondaryBtn" href="/default-values/">Default-value framework</a></div></div></section>
<section className="section"><div className="wrap">
<div className="detailStats"><div><span>Core link</span><strong>Goods → installation</strong></div><div><span>Data types</span><strong>Direct / indirect</strong></div><div><span>Status</span><strong>Verified or pending</strong></div></div>
<div className="detailSection"><div className="sectionLabel">DATA TO ORGANIZE</div><h2>Build a traceable supplier data package</h2><div className="grid"><div className="card"><h3>Product & quantity</h3><p>Keep the CN classification, imported quantity and unit connected to the scenario being assessed.</p></div><div className="card"><h3>Installation & production route</h3><p>Identify where the goods were produced and the relevant production process or route.</p></div><div className="card"><h3>Embedded emissions</h3><p>Record the direct, indirect and precursor information applicable to the goods and methodology used.</p></div></div></div>
<div className="detailSection"><div className="sectionLabel">ACTUAL VS DEFAULT DATA</div><h2>Do not mix data sources without documenting the method</h2><p>Definitive-period rules determine when actual emissions information or an applicable default value may be used. If a default value is used, keep the exact legal source, annex, country or territory, goods category, production route and effective period with the report.</p></div>
<div className="warningBox"><b>Verification matters</b><p>A value supplied by a manufacturer is not automatically the same as a verified value. Track whether supporting evidence has been received, whether verification applies, and what remains pending.</p><span>CBAMSearch treats user-entered emissions values as working data unless independently verified elsewhere.</span></div>
<div className="directoryCta"><div><div className="eyebrow">PUT THE DATA TO WORK</div><h2>Organize supplier and emissions inputs in one report.</h2></div><a className="btn lightBtn" href="/cbam-report/?plan=professional">Create Professional Report →</a></div>
</div></section>
</main>}