export const metadata={title:'How Is CBAM Cost Calculated? Practical Guide',description:'Understand the inputs behind a CBAM planning estimate, including quantity, embedded emissions, certificate price and carbon-price adjustments.',alternates:{canonical:'/guides/cbam-calculation/'}};
export default function Page(){return <main>
<section className="detailHero"><div className="wrap"><div className="eyebrow">CALCULATION GUIDE</div><h1>How is CBAM cost calculated?</h1><p className="lead">A planning estimate combines the imported quantity with the applicable embedded-emissions intensity and certificate-price period, while keeping any eligible carbon-price adjustment traceable.</p><div className="detailActions"><a className="btn" href="/cbam-calculator/">Open calculator</a><a className="btn secondaryBtn" href="/cbam-certificate-price/">Certificate prices</a></div></div></section>
<section className="section"><div className="wrap">
<div className="countryWorkflow"><div><span>01</span><h3>Imported quantity</h3><p>Use the quantity and unit relevant to the goods and reporting period.</p></div><div><span>02</span><h3>Embedded emissions</h3><p>Apply the correct specific embedded-emissions input for the goods and methodology used.</p></div><div><span>03</span><h3>Certificate price</h3><p>Select the published CBAM certificate-price period applicable to the calculation.</p></div><div><span>04</span><h3>Eligible adjustment</h3><p>Record any applicable carbon price paid in the country of origin using the rules and evidence required for the scenario.</p></div></div>
<div className="detailSection"><div className="sectionLabel">SIMPLIFIED PLANNING LOGIC</div><h2>Keep the formula transparent</h2><div className="insightBox"><span>Planning estimate</span><p>Imported quantity × specific embedded emissions × applicable certificate price, adjusted only where a valid carbon-price deduction applies.</p></div><p>This is a planning framework rather than a substitute for the legal calculation rules. The quality of the output depends on the classification, emissions methodology, price period and adjustments entered.</p></div>
<div className="warningBox"><b>A precise number can still be wrong</b><p>Using an incorrect CN code, supplier emissions value or certificate-price period can produce a neat calculation with the wrong basis.</p><span>Keep each input and source with the scenario.</span></div>
<div className="directoryCta"><div><div className="eyebrow">MODEL A SCENARIO</div><h2>Run the calculation with your own inputs.</h2></div><a className="btn lightBtn" href="/cbam-calculator/">Open CBAM calculator →</a></div>
</div></section>
</main>