export const metadata={title:'CBAM CN Code Guide — Classification Before Scope',description:'Learn how EU CN codes connect products to CBAM scope and how to move from an HS code or product description to a usable classification.',alternates:{canonical:'/guides/cbam-cn-code-guide/'}};
export default function Page(){return <main>
<section className="detailHero"><div className="wrap"><div className="eyebrow">CLASSIFICATION GUIDE</div><h1>CBAM CN codes: classify the product before checking scope.</h1><p className="lead">CBAM product scope is classification-driven. Use the most specific EU CN code applicable to the imported goods rather than relying only on a product name or broad HS family.</p><div className="detailActions"><a className="btn" href="/cn-code/">Search CN codes</a><a className="btn secondaryBtn" href="/hs-code/">Start from an HS code</a></div></div></section>
<section className="section"><div className="wrap">
<div className="countryWorkflow threeSteps"><div><span>01</span><h3>Start with the goods</h3><p>Use the technical description, material, form and intended customs classification for the actual imported product.</p></div><div><span>02</span><h3>Find the EU CN code</h3><p>Use an HS prefix as a starting point when needed, then identify the more specific EU Combined Nomenclature record.</p></div><div><span>03</span><h3>Check CBAM scope</h3><p>Compare the exact classification with the applicable CBAM product scope and any recorded exclusions.</p></div></div>
<div className="detailSection"><div className="sectionLabel">COMMON CLASSIFICATION RISKS</div><h2>Why a broad code can mislead a CBAM check</h2><div className="grid"><div className="card"><h3>Product names are not customs codes</h3><p>Commercial descriptions can cover several classifications with different scope outcomes.</p></div><div className="card"><h3>Parent headings can contain exclusions</h3><p>A broader heading can include narrower records that need separate treatment, so the exact code matters.</p></div><div className="card"><h3>HS and CN are not identical</h3><p>The international HS structure is the starting point, while the EU CN adds detail used for EU customs and CBAM research.</p></div></div></div>
<div className="directoryCta"><div><div className="eyebrow">CONTINUE THE WORKFLOW</div><h2>Classification ready?</h2><p>Use the exact code in the scope checker before moving into emissions and cost calculations.</p></div><a className="btn lightBtn" href="/cbam-checker/">Check CBAM scope →</a></div>
<div className="sourceStrip"><div><b>Primary scope reference</b><p>Verify final classification and product scope against current EU customs information and Regulation (EU) 2023/956, Annex I.</p></div><a href="https://eur-lex.europa.eu/eli/reg/2023/956/oj">EU CBAM Regulation →</a></div>
</div></section>
</main>}