export const metadata={title:'CBAM Guides & Resources',description:'Practical guides for CBAM classification, products, emissions, calculations and compliance preparation.',alternates:{canonical:'/guides/'}};
const guides=[
 ['What Is CBAM?','A practical starting point for understanding the mechanism, product scope and the information workflow.','/guides/what-is-cbam/','START HERE'],
 ['CBAM Products & CN Codes','Understand how sector scope and customs classification connect in CBAM research.','/guides/cbam-products-list/','CLASSIFICATION'],
 ['How Is CBAM Cost Calculated?','Learn the inputs behind an indicative exposure calculation and how to use them carefully.','/guides/cbam-calculation/','CALCULATION'],
 ['Guide for Exporters Outside the EU','Prepare product and emissions information for EU customer requests.','/guides/cbam-for-exporters/','EXPORTERS'],
 ['Reporting Requirements','Organize product, emissions and reporting information for a CBAM workflow.','/guides/cbam-reporting-requirements/','REPORTING'],
 ['CN Code Guide','Understand why the exact customs classification matters when checking scope.','/guides/cbam-cn-code-guide/','CN CODES'],
 ['Steel & Aluminium Guide','Explore research considerations for two major industrial product groups.','/guides/cbam-steel-and-aluminium/','SECTORS'],
 ['Guide for Manufacturers','Prepare factory and supplier information for downstream CBAM requests.','/guides/cbam-for-manufacturers/','SUPPLIERS'],
 ['Emissions Data Guide','Understand the role of embedded-emissions inputs and supplier information.','/guides/cbam-emissions-data/','EMISSIONS'],
 ['Importer Guide','A workflow for organizing classification and compliance information for imports.','/guides/cbam-importer-guide/','IMPORTERS'],
 ['Certificate Price Guide','Understand how certificate-price information fits into planning estimates.','/guides/cbam-certificate-price/','PRICING'],
 ['Transition Period Guide','Background on the earlier CBAM transition arrangements and preparation lessons.','/guides/cbam-transition-period/','BACKGROUND']
];
export default function Page(){return <main><section className="directoryHero guideHero"><div className="wrap"><div className="eyebrow">CBAM KNOWLEDGE BASE</div><h1>Practical guidance, connected to the tools.</h1><p className="lead">Learn a concept, check the classification, test a scenario and continue into an assessment without leaving the workflow.</p><div className="heroActions"><a className="btn" href="/cn-code/">Search CN code</a><a className="btn secondaryBtn" href="/cbam-calculator/">Open calculator</a></div></div></section><section className="section"><div className="wrap"><div className="guideGrid">{guides.map(([title,text,href,tag])=><a className="guideCard" href={href} key={href}><span>{tag}</span><h2>{title}</h2><p>{text}</p><b>Read guide →</b></a>)}</div><div className="directoryCta"><div><div className="eyebrow">FROM RESEARCH TO ACTION</div><h2>Ready to organize a real product scenario?</h2></div><a className="btn lightBtn" href="/cbam-report/">Start free assessment →</a></div></div></section></main>}